name: pulmopulse_webapp
description: "Web dashboard for monitoring patient data synced from Apple Health and PulmoPulse questionnaires."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  fl_chart: ^0.65.0
  intl: ^0.18.1
  js: ^0.7.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/pulmopulse_bg.png
  uses-material-design: true
